### ISSUE TITLE
View list of open bugs

### ISSUE THREAD

**Issue by samuelnh** [nogalskisam/Bug-Tracker#6]
As a bug tracker I require the ability to view a list of open bugs so that I can see what bugs are still outstanding within any given system.

Acceptance Criteria
* A list of bugs is available
* The title of the bug is visible in the list
* Only open bugs are visible in the list

**Comment by nogalskisam** [comment]
Requires further detail of whether only open or closed bugs are available to be seen via a search/filter.

**Comment by samuelnh** [comment]
Possible further story to have a filter to show closed bugs also so that we can re-open bugs after they have been closed.
